### ISSUE TITLE
Multilanguage installer

### ISSUE THREAD

**Issue by bovirus** [malikm/HWiNFO#167]
@malikm 

Could be possible to switch ro multilanguage installer.
Your installer seemss based on Inno Setup.
I can help with .iss (Inno Setup Script).
Could be possible to add .iss file to repository?
Which version of Inno Setup are you using? I believe 5.x.

**Comment by malikm** [comment]
ISS 5.4.3 is used. Pretty old but I haven't seen a need to update it yet.
I must admit that I didn't think about a multi-language installer.

**Comment by bovirus** [comment]
@malikm 

If you post the .iss I can enable it in a few minutes.

**Comment by malikm** [comment]
I'm not ready to post this into public now, but can send you privately if you contact me via e-mail of forum PM.
Losing support of XP/2000 would be a problem as the setup is universal also for HWiNFO32 that runs on those systems.

**Comment by bovirus** [comment]
@malikm

I jsut post it to know postive/negative of version of IS 5.x/6.x.

My email is bovirus@gmail.com. Pelase send me .iss file.
When you will send the .iss file. i will edit the post and remove my email refernce.
